////
  The contents of this file are subject to the terms of the Common Development and
  Distribution License (the License). You may not use this file except in compliance with the
  License.

  You can obtain a copy of the License at legal/CDDLv1.0.txt. See the License for the
  specific language governing permission and limitations under the License.

  When distributing Covered Software, include this CDDL Header Notice in each file and include
  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
  Header, with the fields enclosed by brackets [] replaced by your own identifying
  information: "Portions Copyright [year] [name of copyright owner]".

  Copyright 2017 ForgeRock AS.
  Portions Copyright 2024 3A Systems LLC.
////
[#misc-conf]
== Miscellaneous Heap Objects

=== ClientRegistration
Hold OAuth 2.0 client registration information

==== Description
A ClientRegistration holds information about registration with an OAuth 2.0 authorization server or OpenID Provider.

The configuration includes the client credentials that are used to authenticate to the identity provider.
The client credentials can be included directly in the configuration, or retrieved in some other way using an
expression, described in <<Expressions>>.

==== Usage
[source, js]
----
{
  "name": string,
  "type": "ClientRegistration",
  "config": {
    "clientId": expression,
    "clientSecret": expression,
    "issuer": Issuer reference,
    "registrationHandler": Handler reference,
    "scopes": [ expression, ...],
    "tokenEndpointUseBasicAuth": boolean
  }
}
----

==== Properties

The client registration configuration object properties are as follows:

"name": string, required::
A name for the client registration.

"clientId": expression, required::
The `client_id` obtained when registering with the authorization server.
+
See also <<Expressions>>.

"clientSecret": expression, required::
The `client_secret` obtained when registering with the authorization server.
+
See also <<Expressions>>.

"issuer": Issuer reference, required::
The provider configuration to use for this client registration.
+
Provide either the name of a Issuer object defined in the heap, or an inline Issuer configuration object.
+
See also <<Issuer>>.

"registrationHandler": Handler reference, optional::
Invoke this HTTP client handler to communicate with the authorization server.
+
Provide either the name of a Handler object defined in the heap, or an inline Handler configuration object.
+
Usually set this to the name of a ClientHandler configured in the heap, or a chain that ends in a ClientHandler.
+
Default: OpenIG uses the default ClientHandler.
+
See also <<handlers-conf>>, <<ClientHandler>>.

"scopes": array of expressions, optional::
OAuth 2.0 scopes to use with this client registration.
+
See also <<Expressions>>.

"tokenEndpointUseBasicAuth": boolean, optional::
Whether to perform client authentication to the provider using HTTP Basic authentication when sending a request to
the provider's OAuth 2.0 token endpoint.
+
--
When set to `true`, the client credentials are sent using HTTP Basic authentication as in the following example request:

[source, httprequest]
----
POST /oauth2/token HTTP/1.1
Host: as.example.com
Authorization: Basic ....
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=...
----

When set to false, the client credentials are sent in HTTP POST form data as in the following example request:

[source, httprequest]
----
POST /oauth2/token HTTP/1.1
Host: as.example.com
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=.....&client_secret=.....&code=...
----

Some providers accept both authentication methods. For providers that strictly enforce how the client must authenticate,
such as recent versions of OpenAM, you must align the configuration with that of the provider.

If the provider does not support the configured authentication method, then according to RFC 6749
https://datatracker.ietf.org/doc/html/rfc6749#section-5.2[The OAuth 2.0 Authorization Framework, section 5.2]
the provider sends an HTTP 400 Bad Request response with an `invalid_client` error message as in the following example response:

[source, httprequest]
----
HTTP/1.1 400 Bad Request
Content-Type: application/json;charset=UTF-8
Cache-Control: no-store
Pragma: no-cache

{
  "error":"invalid_client"
}
----
Default: `true`
--

==== Example
The following example shows a client registration for OpenAM. In this example client credentials are replaced with
**********. In the actual configuration either include the credentials and protect the configuration file or obtain
the credentials from the environment in a safe manner:

[source, json]
----
{
    "name": "OpenIDConnectRelyingParty",
    "type": "ClientRegistration",
    "config": {
        "clientId": "**********",
        "clientSecret": "**********",
        "issuer": "openam",
        "redirect_uris": [
            "https://openig.example.com:8443/openid/callback"
        ],
        "scopes": [
            "openid",
            "profile"
        ]
    }
}
----

==== Javadoc

https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/filter/oauth2/client/ClientRegistration.html[org.forgerock.openig.filter.oauth2.client.ClientRegistration]

==== See Also

<<Issuer>>, <<OAuth2ClientFilter>>

https://datatracker.ietf.org/doc/html/rfc6749[The OAuth 2.0 Authorization Framework]

https://datatracker.ietf.org/doc/html/rfc6750[OAuth 2.0 Bearer Token Usage]

http://openid.net/connect/[OpenID Connect]


=== JwtSession
Store sessions in encrypted JWT cookies

==== Description

A JwtSession object holds settings for storing session information in encrypted JSON Web Token (JWT) cookies.

In this context, _encrypted JWT cookie_ means an HTTP cookie whose value is an encrypted JWT. The payload of the
encrypted JWT is a JSON representation of the session information.

The JWT cookie lifetime is Session (not persistent), meaning the user-agent deletes the JWT cookie when it shuts down.

When using this storage implementation, you must use data types for session information that can be mapped to
https://json.org/[JavaScript Object Notation (JSON)]. JSON allows strings, numbers, `true`, `false`, `null`, as well as
arrays and JSON objects composed of the same primitives. Java and Groovy types that can be mapped include Java primitive
types and `null`, String and CharSequence objects, as well as List and Map objects.

As browser cookie storage capacity is limited to 4 KB, and encryption adds overhead, take care to limit the size of any
JSON that you store. Rather than store larger data in the session information, consider storing a reference instead.

When a request enters a route that uses a new session type, the scope of the session information becomes limited to the
route. OpenIG builds a new session object and does not propagate any existing session information to the new object.
`session` references the new session object. When the response then exits the route, the session object is closed,
and serialized to a JWT cookie in this case, and `session` references the previous session object. Session information
set inside the route is no longer available.

An HTTP client that performs multiple requests in a session that modify the content of its session can encounter
inconsistencies in the session information. This is because OpenIG does not share JwtSessions across threads.
Instead, each thread has its own JwtSession objects that it modifies as necessary, writing its own session to the JWT
cookie regardless of what other threads do.

==== Usage
[source, js]
----
{
    "name": string,
    "type": "JwtSession",
    "config": {
        "keystore": KeyStore reference,
        "alias": string,
        "password": configuration expression,
        "cookieName": string,
        "sessionTimeout": duration,
        "sharedSecret": string
    }
}
----

An alternative value for type is JwtSessionFactory.

==== Properties

"keystore": KeyStore reference, optional::
The keystore holding the key pair with the private key used to decrypt the JWT.
+
Provide either the name of the KeyStore object defined in the heap, or the inline KeyStore configuration object inline.
+
Default: When no keystore is specified, OpenIG generates a unique key pair, and stores the key pair in memory.
With JWTs encrypted using a unique key pair generated at runtime, OpenIG cannot decrypt the JWTs after a restart,
nor can it decrypt such JWTs encrypted by another OpenIG server.
+
See also <<KeyStore>>.

"alias": string, required when keystore is used::
Alias for the private key.

"password": configuration expression, required when keystore is used::
The password to read the private key from the keystore.
+
A configuration expression, described in <<Expressions>> is independent of the request, response, and contexts,
so do not use expressions that reference their properties. You can, however, use `$+{env['variable']}+`,
`$+{system['property']}+`, and all the built-in functions listed in <<Functions>>.

"cookieName" string, optional::
The name of the JWT cookie stored on the user-agent.
+
Default: `openig-jwt-session`

"sessionTimeout" duration, optional::
The amount of time before the cookie session expires.
+
A duration is a lapse of time expressed in English, such as `23 hours 59 minutes and 59 seconds`.
+
Durations are not case sensitive.
+
Negative durations are not supported.
+
The following units can be used in durations:
+
* `indefinite`, `infinity`, `undefined`, `unlimited`: unlimited duration
* `zero`, `disabled`: zero-length duration
* `days`, `day`, `d`: days
* `hours`, `hour`, `h`: hours
* `minutes`, `minute`, `min`, `m`: minutes
* `seconds`, `second`, `sec`, `s`: seconds
* `milliseconds`, `millisecond`, `millisec`, `millis`, `milli`, `ms`: milliseconds
* `microseconds`, `microsecond`, `microsec`, `micros`, `micro`, `us`: microseconds
* `nanoseconds`, `nanosecond`, `nanosec`, `nanos`, `nano`, `ns`: nanoseconds
+
Default: 30 minutes
+
A zero duration for session timeout is not a valid setting. The maximum session timeout duration is 3650 days
(approximately 10 years). If you set a longer duration, OpenIG truncates the duration to the maximum value.

"sharedSecret" string, optional::
Specifies the key used to sign and verify the JWTs.
+
This attribute is expected to be base-64 encoded. The minimum key size after base-64 decoding is 32 bytes/256 bits
(HMAC-SHA-256 is used to sign JWTs). If the provided key is too short, an error message is created.
+
If this attribute is not specified, random data is generated as the key, and the OpenIG instance can verify only
the sessions it has created.

==== Example
The following example defines a JwtSession for storing session information in a JWT token cookie named OpenIG.
The JWT is encrypted with a private key that is recovered using the alias private-key, and stored in the keystore.
The password is both the password for the keystore and also the private key:

[source, json]
----
{
    "name": "JwtSession",
    "type": "JwtSession",
    "config": {
        "keystore": {
            "type": "KeyStore",
            "config": {
                "url": "file://${env['HOME']}/keystore.jks",
                "password": "${system['keypass']}"
            }
        },
        "alias": "private-key",
        "password": "${system['keypass']}",
        "cookieName": "OpenIG"
    }
}
----

==== Javadoc
https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/jwt/JwtSessionManager.html[org.forgerock.openig.jwt.JwtSessionManager]

=== KeyManager
Configure a Java Secure Socket Extension KeyManager

==== Description
This represents the configuration for a Java Secure Socket Extension
https://docs.oracle.com/javase/8/docs/api/index.html?javax/net/ssl/KeyManager.html[KeyManager], which manages the keys
used to authenticate an SSLSocket to a peer. The configuration references the keystore that actually holds the keys.

==== Usage
[source, js]
----
{
    "name": string,
    "type": "KeyManager",
    "config": {
        "keystore": KeyStore reference,
        "password": expression,
        "alg": string
    }
}
----

==== Properties

"keystore": KeyStore reference, optional::
The keystore that references the store for the actual keys.
+
Provide either the name of the KeyStore object defined in the heap, or the inline KeyStore configuration object inline.
+
See also <<KeyStore>>.

"password": expression, required::
The password to read private keys from the keystore.

"alg" string, optional::
The certificate algorithm to use.
+
Default: the default for the platform, such as `SunX509`.
+
See also <<Expressions>>.

==== Example
The following example configures a key manager that depends on a KeyStore configuration. The keystore takes a password
supplied as a Java system property when starting the container where OpenIG runs, as in `-Dkeypass=password`.
This configuration uses the default certificate algorithm:

[source, json]
----
{
    "name": "MyKeyManager",
    "type": "KeyManager",
    "config": {
        "keystore": {
            "type": "KeyStore",
            "config": {
                "url": "file://${env['HOME']}/keystore.jks",
                "password": "${system['keypass']}"
            }
        },
        "password": "${system['keypass']}"
    }
}
----

==== Javadoc
https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/security/KeyManagerHeaplet.html[org.forgerock.openig.security.KeyManagerHeaplet]

==== See Also
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html[JSSE Reference Guide],
<<KeyStore>>, <<TrustManager>>

=== KeyStore
Configure a Java KeyStore

==== Description
This represents the configuration for a Java
https://docs.oracle.com/javase/8/docs/api/index.html?java/security/KeyStore.html[KeyStore], which stores cryptographic
private keys and public key certificates.

==== Usage
[source, js]
----
{
    "name": name,
    "type": "KeyStore",
    "config": {
        "url": expression,
        "password": expression,
        "type": string
    }
}
----

==== Properties
"url": expression, required::
URL to the keystore file.
+
See also <<Expressions>>.

"password": expression, optional::
The password to read private keys from the keystore.
+
If the keystore is used as a truststore to store only public key certificates of peers and no password is required
to do so, then you do not have to specify this field.
+
Default: No password is set.
+
See also <<Expressions>>.

"type": string, optional::
The keystore format.
+
Default: the default for the platform, such as `JKS`.

==== Example
The following example configures a keystore that references a Java Keystore file, `$HOME/keystore.jks`. The keystore
takes a password supplied as a Java system property when starting the container where OpenIG runs, as in
`-Dkeypass=password`. As the keystore file uses the default format, no type is specified:

[source, json]
----
{
    "name": "MyKeyStore",
    "type": "KeyStore",
    "config": {
        "url": "file://${env['HOME']}/keystore.jks",
        "password": "${system['keypass']}"
    }
}
----

==== Javadoc
https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/security/KeyStoreHeaplet.html[org.forgerock.openig.security.KeyStoreHeaplet]

See Also
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html[JSSE Reference Guide],
<<KeyManager>>, <<TrustManager>>

=== Issuer
Describe an Authorization Server or OpenID Provider

==== Description
An Issuer describes an OAuth 2.0 Authorization Server or an OpenID Provider that OpenIG can use as a OAuth 2.0 client
or OpenID Connect relying party.
+
An Issuer is generally referenced from a ClientRegistration, described in <<ClientRegistration>>.

==== Usage
[source, js]
----
{
  "name": string,
  "type": "Issuer",
  "config": {
    "wellKnownEndpoint": URL string,
    "authorizeEndpoint": URI expression,
    "registrationEndpoint": URI expression,
    "tokenEndpoint": URI expression,
    "userInfoEndpoint": URI expression,
    "issuerHandler": Handler reference,
    "supportedDomains": [ domain pattern, ... ]
  }
}
----

==== Properties

If the provider has a well-known configuration URL as defined for OpenID Connect 1.0 Discovery that returns JSON with
at least authorization and token endpoint URLs, then you can specify that URL in the provider configuration.
Otherwise, you must specify at least the provider authorization and token endpoint URLs, and optionally the
registration endpoint and user info endpoint URLs.

The provider configuration object properties are as follows:

"name": string, required::
A name for the provider configuration.

"wellKnownEndpoint": URL string, required unless authorizeEndpoint and tokenEndpoint are specified::
The URL to the well-known configuration resource as described in OpenID Connect 1.0 Discovery.

"authorizeEndpoint": expression, required unless obtained through wellKnownEndpoint::
The URL to the provider's OAuth 2.0 authorization endpoint.
+
See also <<Expressions>>.

"registrationEndpoint": expression, optional::
The URL to the provider's OpenID Connect dynamic registration endpoint.
+
See also <<Expressions>>.

"tokenEndpoint": expression, required unless obtained through wellKnownEndpoint
The URL to the provider's OAuth 2.0 token endpoint.
+
See also <<Expressions>>.

"userInfoEndpoint": expression, optional::
The URL to the provider's OpenID Connect UserInfo endpoint.
+
Default: no UserInfo is obtained from the provider.
+
See also Expressions.

"issuerHandler": Handler reference, optional::
Invoke this HTTP client handler to communicate with the authorization server.
+
Provide either the name of a Handler object defined in the heap, or an inline Handler configuration object.
+
Usually set this to the name of a ClientHandler configured in the heap, or a chain that ends in a ClientHandler.
+
Default: OpenIG uses the default ClientHandler.
+
See also <<handlers-conf>>, <<ClientHandler>>.

"supportedDomains": array of patterns, optional::
List of patterns matching domain names handled by this issuer, used as a shortcut for
https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect discovery] before performing
https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect dynamic registration].
+
In summary when the OpenID Provider is not known in advance, it might be possible to discover the OpenID Provider
Issuer based on information provided by the user, such as an email address. The OpenID Connect discovery specification
explains how to use https://datatracker.ietf.org/doc/html/rfc7033[WebFinger] to discover the issuer.
OpenIG can discover the issuer in this way. As a shortcut OpenIG can also use supported domains lists to find
issuers already described in the OpenIG configuration.
+
To use this shortcut, OpenIG extracts the domain from the user input, and looks for an issuer whose supported domains
list contains a match.
+
Supported domains patterns match host names with optional port numbers. Do not specify a URI scheme such as HTTP.
OpenIG adds the scheme. For instance, `*.example.com` matches any host in the `example.com` domain. You can specify
the port number as well as in `host.example.com:8443`. Patterns must be valid regular expression patterns according
to the rules for the Java https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html[Pattern] class.


==== Examples
The following example shows an OpenAM issuer configuration for OpenAM. OpenAM exposes a well-known endpoint for the
provider configuration, but this example demonstrates use of the other fields:

[source, json]
----
{
    "name": "openam",
    "type": "Issuer",
    "config": {
        "authorizeEndpoint":
          "https://openam.example.com:8443/openam/oauth2/authorize",
        "registration_endpoint":
          "https://openam.example.com:8443/openam/oauth2/connect/register",
        "tokenEndpoint":
          "https://openam.example.com:8443/openam/oauth2/access_token",
        "userInfoEndpoint":
          "https://openam.example.com:8443/openam/oauth2/userinfo",
        "supportedDomains": [ "mail.example.*", "docs.example.com:8443" ]
    }
}
----

The following example shows an issuer configuration for Google:
[source, json]
----
{
    "name": "google",
    "type": "Issuer",
    "config": {
        "wellKnownEndpoint":
          "https://accounts.google.com/.well-known/openid-configuration",
        "supportedDomains": [ "gmail.*", "googlemail.com:8052" ]
    }
}
----

==== Javadoc
https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/filter/oauth2/client/Issuer.html[org.forgerock.openig.filter.oauth2.client.Issuer]

=== ScheduledExecutorService
Schedule the execution of tasks

==== Description
An executor service to schedule tasks for execution after a delay or for repeated execution with a fixed interval of
time in between each execution. You can configure the number of threads in the executor service and how the executor
service is stopped.

The `ScheduledExecutorService` is shared by all downstream components that use an executor service.

==== Usage

[source, js]
----
{
    "name": string,
    "type": "ScheduledExecutorService",
    "config": {
        "corePoolSize”:  integer or expression<integer>,
        "gracefulStop":  boolean or expression<boolean>,
        "gracePeriod" :  duration string or expression<duration string>
    }
}
----

==== Properties

"corePoolSize": integer or expression<integer>, optional::
The minimum number of threads to keep in the pool. If this property is an expression, the expression is evaluated as
soon as the configuration is read.
+
The value must be an integer greater than zero.
+
Default: 1

"gracefulStop": boolean or expression<boolean> , optional::
Defines how the executor service stops. If this property is an expression, the expression is evaluated as soon as
the configuration is read.
+
--
If true, the executor service does the following:

* Blocks the submission of new jobs.
* Allows running jobs to continue.
* If a grace period is defined, waits for up to that maximum time for running jobs to finish before it stops.

If false, the executor service does the following:

* Blocks the submission of new jobs.
* Removes submitted jobs without running them.
* Attempts to end running jobs.
* If a grace period is defined, ignores it.

Default: true
--

"gracePeriod": duration string or expression<duration string>, optional::
The maximum time that the executor service waits for running jobs to finish before it stops. If this property is an
expression, the expression is evaluated as soon as the configuration is read.
+
If all jobs finish before the grace period, the executor service stops without waiting any longer. If jobs are still
running after the grace period, the executor service stops anyway and prints a message.
+
When `gracefulStop` is `false`, the grace period is ignored.
+
A duration is a lapse of time expressed in English, such as `23 hours 59 minutes and 59 seconds`.
+
Durations are not case sensitive.
+
Negative durations are not supported.
+
The following units can be used in durations:
+
* `indefinite`, `infinity`, `undefined`, `unlimited`: unlimited duration
* `zero`, `disabled`: zero-length duration
* `days`, `day`, `d`: days
* `hours`, `hour`, `h`: hours
* `minutes`, `minute`, `min`, `m`: minutes
* `seconds`, `second`, `sec`, `s`: seconds
* `milliseconds`, `millisecond`, `millisec`, `millis`, `milli`, `ms`: milliseconds
* `microseconds`, `microsecond`, `microsec`, `micros`, `micro`, `us`: microseconds
* `nanoseconds`, `nanosecond`, `nanosec`, `nanos`, `nano`, `ns`: nanoseconds

+
Default: 10 seconds

==== Example
The following example creates a thread pool to execute tasks. When the executor service is instructed to stop,
it blocks the submission of new jobs, and waits for up to 10 seconds for submitted and running jobs to complete
before it stops. If any jobs are still submitted or running after 10 seconds, the executor service stops anyway and
prints a message.

[source, json]
----
{
    "name": "ExecutorService",
    "comment": "Default service for executing tasks in the background.",
    "type": "ScheduledExecutorService",
    "config": {
        "corePoolSize": 5,
        "gracefulStop": true,
        "gracePeriod": "10 seconds"
    }
}
----

==== Javadoc

https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/thread/ScheduledExecutorServiceHeaplet.html[org.forgerock.openig.thread.ScheduledExecutorServiceHeaplet]


=== TemporaryStorage
Cache streamed content

==== Description
Allocates temporary buffers for caching streamed content during request processing. Initially uses memory; when the
memory limit is exceeded, switches to a temporary file.

==== Usage
[source, js]
----
{
     "name": string,
     "type": "TemporaryStorage",
     "config": {
         "initialLength": number,
         "memoryLimit": number,
         "fileLimit": number,
         "directory": string
     }
}
----

==== Properties
"initialLength": number, optional::
The initial length of memory buffer byte array.
+
Default: 8192 (8 KiB).

"memoryLimit": number, optional::
The length limit of the memory buffer. Exceeding this limit results in promotion from memory to file.
+
Default: 65536 (64 KiB).

"fileLimit": number, optional::
The length limit of the file buffer. Exceeding this limit results in a thrown exception.
+
Default: 1048576 (1 MiB).

"directory": string, optional::
The directory where temporary files are created. If omitted, then the system-dependent default temporary directory is
used (typically `"/tmp"` on Unix systems). Default: use system-dependent default.

==== Javadoc
https://doc.openidentityplatform.org/openig/apidocs/org/forgerock/openig/io/TemporaryStorageHeaplet.html[org.forgerock.openig.io.TemporaryStorageHeaplet]

=== TrustManager
Configure a Java Secure Socket Extension TrustManager

==== Description

This represents the configuration for a Java Secure Socket Extension
https://docs.oracle.com/javase/8/docs/api/index.html?javax/net/ssl/TrustManager.html[TrustManager], which manages the
trust material (typically X.509 public key certificates) used to decide whether to accept the credentials presented by
a peer. The configuration references the keystore that actually holds the trust material.



















